import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/shared/Header";
import { cn } from "@/lib/utils";
import { ClerkProvider } from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Links",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={cn(inter.className, "min-h-screen flex flex-col")}>
          {/* <Toaster /> */}

          {/* Header */}
          <header className="border-b sticky top-0 bg-white z-50">
            <Header />
          </header>

          <main className=" bg-[#F4F2ED] flex-1 w-full">{children}</main>
        </body>
      </html>
    </ClerkProvider>
  );
}
